export type EmojiCategory = {
  id: string
  label: string
  emojis: { glyph: string; name: string }[]
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: 'smileys',
    label: 'Smileys',
    emojis: [
      { glyph: '😀', name: 'grinning' },
      { glyph: '😃', name: 'smiley' },
      { glyph: '😄', name: 'smile' },
      { glyph: '😁', name: 'grin' },
      { glyph: '😅', name: 'sweat smile' },
      { glyph: '😂', name: 'joy' },
      { glyph: '🤣', name: 'rofl' },
      { glyph: '😊', name: 'blush' },
      { glyph: '😇', name: 'innocent' },
      { glyph: '🙂', name: 'slight smile' },
      { glyph: '😉', name: 'wink' },
      { glyph: '😍', name: 'heart eyes' },
      { glyph: '🥰', name: 'smiling hearts' },
      { glyph: '😘', name: 'kiss' },
      { glyph: '😜', name: 'stuck out tongue' },
      { glyph: '🤔', name: 'thinking' },
      { glyph: '🤨', name: 'raised eyebrow' },
      { glyph: '😐', name: 'neutral' },
      { glyph: '😏', name: 'smirk' },
      { glyph: '😢', name: 'cry' },
      { glyph: '😭', name: 'sob' },
      { glyph: '😤', name: 'triumph' },
      { glyph: '😡', name: 'rage' },
      { glyph: '🥳', name: 'party' },
      { glyph: '😴', name: 'sleeping' },
      { glyph: '😷', name: 'mask' },
      { glyph: '🤯', name: 'exploding head' },
      { glyph: '😎', name: 'sunglasses' },
    ],
  },
  {
    id: 'people',
    label: 'People',
    emojis: [
      { glyph: '👍', name: 'thumbs up' },
      { glyph: '👎', name: 'thumbs down' },
      { glyph: '👏', name: 'clap' },
      { glyph: '🙌', name: 'raised hands' },
      { glyph: '🤝', name: 'handshake' },
      { glyph: '🙏', name: 'pray' },
      { glyph: '💪', name: 'muscle' },
      { glyph: '✌️', name: 'v' },
      { glyph: '🤞', name: 'crossed fingers' },
      { glyph: '👋', name: 'wave' },
      { glyph: '🫡', name: 'salute' },
      { glyph: '👀', name: 'eyes' },
      { glyph: '🧠', name: 'brain' },
      { glyph: '❤️', name: 'heart' },
      { glyph: '💔', name: 'broken heart' },
      { glyph: '🔥', name: 'fire' },
      { glyph: '✨', name: 'sparkles' },
      { glyph: '💯', name: 'hundred' },
    ],
  },
  {
    id: 'nature',
    label: 'Nature',
    emojis: [
      { glyph: '🐶', name: 'dog' },
      { glyph: '🐱', name: 'cat' },
      { glyph: '🐭', name: 'mouse' },
      { glyph: '🦊', name: 'fox' },
      { glyph: '🐻', name: 'bear' },
      { glyph: '🐼', name: 'panda' },
      { glyph: '🌸', name: 'cherry blossom' },
      { glyph: '🌲', name: 'evergreen' },
      { glyph: '🍀', name: 'clover' },
      { glyph: '🌍', name: 'earth' },
      { glyph: '⭐', name: 'star' },
      { glyph: '🌙', name: 'moon' },
      { glyph: '☀️', name: 'sun' },
      { glyph: '⚡', name: 'zap' },
      { glyph: '❄️', name: 'snowflake' },
      { glyph: '💧', name: 'droplet' },
    ],
  },
  {
    id: 'food',
    label: 'Food',
    emojis: [
      { glyph: '🍎', name: 'apple' },
      { glyph: '🍕', name: 'pizza' },
      { glyph: '🍔', name: 'burger' },
      { glyph: '🍟', name: 'fries' },
      { glyph: '🍣', name: 'sushi' },
      { glyph: '🍜', name: 'ramen' },
      { glyph: '☕', name: 'coffee' },
      { glyph: '🍵', name: 'tea' },
      { glyph: '🍺', name: 'beer' },
      { glyph: '🍷', name: 'wine' },
      { glyph: '🍰', name: 'cake' },
      { glyph: '🍪', name: 'cookie' },
      { glyph: '🍩', name: 'doughnut' },
      { glyph: '🍦', name: 'ice cream' },
    ],
  },
  {
    id: 'activities',
    label: 'Activities',
    emojis: [
      { glyph: '⚽', name: 'soccer' },
      { glyph: '🏀', name: 'basketball' },
      { glyph: '🎮', name: 'video game' },
      { glyph: '🎯', name: 'dart' },
      { glyph: '🎵', name: 'music' },
      { glyph: '🎧', name: 'headphones' },
      { glyph: '🎬', name: 'clapper' },
      { glyph: '📸', name: 'camera' },
      { glyph: '✈️', name: 'airplane' },
      { glyph: '🚗', name: 'car' },
      { glyph: '🏠', name: 'house' },
      { glyph: '💡', name: 'bulb' },
      { glyph: '📱', name: 'phone' },
      { glyph: '💻', name: 'laptop' },
      { glyph: '⌚', name: 'watch' },
      { glyph: '🎁', name: 'gift' },
      { glyph: '🎉', name: 'tada' },
      { glyph: '✅', name: 'check' },
      { glyph: '❌', name: 'x' },
      { glyph: '⚠️', name: 'warning' },
    ],
  },
]

/** Top reactions shown inline; “＋” opens the full emoji picker for the rest. */
export const QUICK_REACTIONS = ['👍', '❤️', '😂', '😮', '😢'] as const
